// <auto-generated />
namespace SamaService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202109150348160_dbcreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
